class CharData {
  static final List<Map<String, dynamic>> data = [
    {
      "name": "Lucia: Plume",
      "role": "Attacker",
      "weapon": "Katana - Crimson Birch",
      "faction": "Gray Raven",
      "info": "Babylonia developed this latest frame specifically for Lucia based on Gray Raven's experience and the data collected from Alpha.",
      "element": "Physical (20%) Ice (80%)",
      "banner": "images/plume_banner.png",
      "profile": "images/plume_profile.png",
      "img_faction": "images/faction_gr.png",
      "img_role": "images/class_attacker.png",
      "link": "https://grayravens.com/wiki/Lucia:_Plume"
    },
    {
      "name": "Lucia: Crimson Abyss",
      "role": "Attacker",
      "weapon": "Katana - Sakura",
      "faction": "Ascendant",
      "info": "A mysterious enemy encountered by Gray Raven in City 015. Powerful yet mercurial.",
      "element": "Physical (100%)",
      "banner": "images/alpha_banner.png",
      "profile": "images/alpha_profile.png",
      "img_faction": "images/faction_ascendant.png",
      "img_role": "images/class_attacker.png",
      "link": "https://grayravens.com/wiki/Lucia:_Crimson_Abyss"
    },
    {
      "name": "Luna: Laurel",
      "role": "Attacker",
      "weapon": "Amplifier - Ozma",
      "faction": "Ascendant",
      "info": "As an Agent of the Ascension-Network, this is her complete combat form, in which she can manipulate the Heteromer energy of the Punishing Virus and Constructs to deliver attacks with a power that transcends all Ascendants.",
      "element": "Physical (10%) Dark (90%)",
      "banner": "images/laurel_banner.png",
      "profile": "images/profile_laurel.png",
      "img_faction": "images/faction_ascendant.png",
      "img_role": "images/class_attacker.png",
      "link": "https://grayravens.com/wiki/Luna:_Laurel"
    },
    {
      "name": "Rosetta: Rigor",
      "role": "Tank",
      "weapon": "Spear Shield - Gungnir",
      "faction": "Arctic Route Union",
      "info": "Leader of the original Forest Guard, Rosetta has been taken in by Babylonia, designated as a special unit, and redeployed onto the battlefield in a more humanoid form.",
      "element": "Physical (100%)",
      "banner": "images/rigor_banner.png",
      "profile": "images/rigor_profile.png",
      "img_faction": "images/faction_aru.png",
      "img_role": "images/class_tank.png",
      "link": "https://grayravens.com/wiki/Rosetta:_Rigor"
    },
    {
      "name": "Chrome: Glory",
      "role": "Tank",
      "weapon": "Gunblade - Apollo",
      "faction": "Strike Hawk",
      "info": "The second specialized frame of Babylonia's mid-term military Construct development plan. It has been adjusted and optimized based on Chrome's request.",
      "element": "Physical (20%) Ice (80%)",
      "banner": "images/glory_banner.png",
      "profile": "images/glory_profile.png",
      "img_faction": "images/faction_sh.png",
      "img_role": "images/class_tank.png",
      "link": "https://grayravens.com/wiki/Chrome:_Glory"
    },
    {
      "name": "Vera: Garnet",
      "role": "Tank",
      "weapon": "Banner Spear - Phoenix",
      "faction": "Cerberus",
      "info": "A frame Vera used in the past. Designed as an advanced, decisive countermeasure against hostile Constructs, it was finally introduced as an official unit not long ago. Its weapon is a specially forged banner spear.",
      "element": "Physical (15%) Lightning (85%)",
      "banner": "images/garnet_banner.png",
      "profile": "images/garnet_profile.png",
      "img_faction": "images/faction_cerberus.png",
      "img_role": "images/class_tank.png",
      "link": "https://grayravens.com/wiki/Vera:_Garnet"
    },
    {
      "name": "Liv: Empyrea",
      "role": "Amplifier",
      "weapon": "Scepter - Hestia",
      "faction": "Gray Raven",
      "info": "A brand new specialized frame developed by the Science Council that is capable of \"purifying\" the Punishing Virus. To protect everything she loves, Liv has made her own choice.",
      "element": "Physical (10%) Fire (90%)",
      "banner": "images/empyrea_banner.png",
      "profile": "images/empyrea_profile.png",
      "img_faction": "images/faction_gr.png",
      "img_role": "images/class_amplifier.png",
      "link": "https://grayravens.com/wiki/Liv:_Empyrea"
    },
    {
      "name": "Selena: Capriccio",
      "role": "Amplifier",
      "weapon": "Flute Sword - Sarastro",
      "faction": "World Government Association of Art",
      "info": "Selena's backup frame. Made with the support of an artist from WGAA, it is free-spirited and lively like its namesake, but the sentiments it embodies are earnest and solemn.",
      "element": "Physical (10%) Dark (90%)",
      "banner": "images/capriccio_banner.png",
      "profile": "images/capriccio_profile.png",
      "img_faction": "images/faction_wgaa.png",
      "img_role": "images/class_amplifier.png",
      "link": "https://grayravens.com/wiki/Selena:_Capriccio"
    },
    {
      "name": "Camu: Crocotta",
      "role": "Vanguard",
      "weapon": "Greatsword - Thanatos",
      "faction": "Strike Hawk",
      "info": "A Transcendant that was once a repressed alter-ego in Kamui's M.I.N.D., Camu has been given his own unit by Babylonia, and now specializes in operations in and around heavily-Corrupted Dead Zones.",
      "element": "Physical (20%) Dark (80%)",
      "banner": "images/camu_banner.png",
      "profile": "images/camu_profile.png",
      "img_faction": "images/faction_sh.png",
      "img_role": "images/class_vanguard.png",
      "link": "https://grayravens.com/wiki/Camu:_Crocotta"
    },
    {
      "name": "Qu: Pavo",
      "role": "Vanguard",
      "weapon": "Glaive - Qinghe",
      "faction": "Kowloong Chamber of Commerce",
      "info": "A Transcendant and the last head of Kowloong. After the Battle of Kowloong, she has gone into hiding and continued with her ambition to achieve the Tabula Akasha.",
      "element": "Physical (100%)",
      "banner": "images/pavo_banner.png",
      "profile": "images/pavo_profile.png",
      "img_faction": "images/faction_kcc.png",
      "img_role": "images/class_vanguard.png",
      "link": "https://grayravens.com/wiki/Qu:_Pavo"
    },
    {
      "name": "Pulao: Dragontoll",
      "role": "Vanguard",
      "weapon": "Dragon Maelstrom - Infinity",
      "faction": "Kowloong Chamber of Commerce",
      "info": "The frame of Pulao, one of the Dragon Children, is not made from conventional components but has been carefully adapted to fit her M.I.N.D., allowing her to make the most of her unusually strong powers.",
      "element": "Physical (100%)",
      "banner": "images/pulao_banner.png",
      "profile": "images/pulao_profile.png",
      "img_faction": "images/faction_kcc.png",
      "img_role": "images/class_vanguard.png",
      "link": "https://grayravens.com/wiki/Pulao:_Dragontoll"
    },
  ];
}

